# --- Just test data

# --- !Ups
insert into team(id, name) values(1, 'Real Madrid Club De Fútbol');
insert into team(id, name) values(2, 'FC Barcelona');
insert into team(id, name) values(3, 'Arsenal');
insert into team(id, name) values(4, 'Milan');
insert into team(id, name) values(5, 'Manchester United');
insert into team(id, name) values(6, 'Borussia Dortmund');
insert into team(id, name) values(7, 'Chelsea');
insert into team(id, name) values(8, 'Juventus');
insert into team(id, name) values(9, 'Liverpool');
insert into team(id, name) values(10, 'Bayern München');
insert into team(id, name) values(11, 'Manchester City');
insert into team(id, name) values(12, 'Paris Saint-Germain');
insert into team(id, name) values(13, 'Tottenham Hotspur');
insert into team(id, name) values(14, 'Inter');
insert into team(id, name) values(15, 'Galatasaray SK');
insert into team(id, name) values(16, 'Club Atlético De Madrid SAD');
insert into team(id, name) values(17, 'Newcastle United');
insert into team(id, name) values(18, 'Roma');
insert into team(id, name) values(19, 'FC Porto');
insert into team(id, name) values(20, 'FC Schalke');
insert into team(id, name) values(21, 'Ajax');
insert into team(id, name) values(22, 'Málaga Club De Fútbol SAD');
insert into team(id, name) values(23, 'Napoli');
insert into team(id, name) values(24, 'Everton');
insert into team(id, name) values(25, 'Olympique Lyonnais');
insert into team(id, name) values(26, 'Valencia Club De Fútbol SAD');
insert into team(id, name) values(27, 'Aston Villa');
insert into team(id, name) values(28, 'ACF Fiorentina');
insert into team(id, name) values(29, 'Sport Lisboa Benfica');
insert into team(id, name) values(30, 'Queens Park Rangers');
insert into team(id, name) values(31, 'Southampton');
insert into team(id, name) values(32, 'Santos');
insert into team(id, name) values(33, 'Fútbol Club Barcelona “B”');
insert into team(id, name) values(34, 'Lazio');
insert into team(id, name) values(35, 'Swansea City');
insert into team(id, name) values(36, 'VfL Wolfsburg');
insert into team(id, name) values(37, 'Feyenoord');
insert into team(id, name) values(38, 'Corinthians');
insert into team(id, name) values(39, 'Anzhi Makhachkala');
insert into team(id, name) values(40, 'Sporting CP');
insert into team(id, name) values(41, 'Olympique De Marseille');
insert into team(id, name) values(42, 'Hamburger SV');
insert into team(id, name) values(43, 'Bayer  Leverkusen');
insert into team(id, name) values(44, 'AS Saint-Etienne');
insert into team(id, name) values(45, 'Borussia M''gladbach');
insert into team(id, name) values(46, 'PSV');
insert into team(id, name) values(47, 'São Paulo');
insert into team(id, name) values(48, 'Werder Bremen');
insert into team(id, name) values(49, 'LOSC Lille Métropole');
insert into team(id, name) values(50, 'Athletic Club De Bilbao');
insert into team(id, name) values(51, 'CSKA Moskva');
insert into team(id, name) values(52, 'Udinese');
insert into team(id, name) values(53, 'Zenit St Petersburg');
insert into team(id, name) values(54, 'Sevilla Fútbol Club SAD');
insert into team(id, name) values(55, 'West Ham United');
insert into team(id, name) values(56, 'Fulham');
insert into team(id, name) values(57, 'Celtic');
insert into team(id, name) values(58, 'Villarreal Club De Fútbol SAD');
insert into team(id, name) values(59, 'Sunderland');
insert into team(id, name) values(60, 'Spartak Moskva');
insert into team(id, name) values(61, 'Atlético Mineiro');
insert into team(id, name) values(62, 'AS Monaco FC');
insert into team(id, name) values(63, 'Flamengo');
insert into team(id, name) values(64, 'Real Sociedad De Fútbol SAD');
insert into team(id, name) values(65, 'Real Madrid Castilla');
insert into team(id, name) values(66, 'Wigan Athletic');
insert into team(id, name) values(67, 'West Bromwich Albion');
insert into team(id, name) values(68, 'Grêmio');
insert into team(id, name) values(69, 'River Plate');
insert into team(id, name) values(70, 'Sampdoria');
insert into team(id, name) values(71, 'Genoa');
insert into team(id, name) values(72, 'Palermo');
insert into team(id, name) values(73, 'Blackburn Rovers');
insert into team(id, name) values(74, 'Stoke City');
insert into team(id, name) values(75, 'RSC Anderlecht');
insert into team(id, name) values(76, 'Bolton Wanderers');
insert into team(id, name) values(77, 'América');
insert into team(id, name) values(78, 'Hannover');
insert into team(id, name) values(79, 'Real Club Deportivo De La Coruña SAD');
insert into team(id, name) values(80, 'F Torino');
insert into team(id, name) values(81, 'Fluminense');
insert into team(id, name) values(82, 'Norwich City');
insert into team(id, name) values(83, 'VfB Stuttgart');
insert into team(id, name) values(84, 'Leeds United');
insert into team(id, name) values(85, 'FC Nürnberg');
insert into team(id, name) values(86, 'Boca Juniors');
insert into team(id, name) values(87, 'Girondins De Bordeaux');
insert into team(id, name) values(88, 'Internacional');
insert into team(id, name) values(89, 'Vitesse');
insert into team(id, name) values(90, 'Parma');
insert into team(id, name) values(91, 'Real Betis Balompié SAD');
insert into team(id, name) values(92, 'Los Angeles Galaxy');
insert into team(id, name) values(93, 'Crystal Palace');
insert into team(id, name) values(94, 'Standard De Liège');
insert into team(id, name) values(95, 'Toulouse FC');
insert into team(id, name) values(96, 'AZ Alkmaar');
insert into team(id, name) values(97, 'Cagliari');
insert into team(id, name) values(98, 'Birmingham City');
insert into team(id, name) values(99, 'Bologna');
insert into team(id, name) values(100, 'Eintracht Frankfurt');
insert into team(id, name) values(101, 'Atalanta');
insert into team(id, name) values(102, 'Rangers');
insert into team(id, name) values(103, 'Montpellier Hérault Sport Club');
insert into team(id, name) values(104, 'Guadalajara');
insert into team(id, name) values(105, 'OGC Nice');
insert into team(id, name) values(106, 'Palmeiras');
insert into team(id, name) values(107, 'Brescia');
insert into team(id, name) values(108, 'Cruzeiro');
insert into team(id, name) values(109, 'Watford');
insert into team(id, name) values(110, 'New York Red Bulls');
insert into team(id, name) values(111, 'Stade Rennais FC');
insert into team(id, name) values(112, 'Rubin Kazan');
insert into team(id, name) values(113, 'Olympiakos CFP');
insert into team(id, name) values(114, 'Catania');
insert into team(id, name) values(115, 'FC Twente');
insert into team(id, name) values(116, 'Hertha BSC');
insert into team(id, name) values(117, 'Wolverhampton Wanderers');
insert into team(id, name) values(118, 'FC Köln');
insert into team(id, name) values(119, 'Leicester City');
insert into team(id, name) values(120, 'TSG  Hoffenheim');
insert into team(id, name) values(121, 'Nottingham Forest');
insert into team(id, name) values(122, 'Pescara');
insert into team(id, name) values(123, 'FSV Mainz');
insert into team(id, name) values(124, 'Portsmouth');
insert into team(id, name) values(125, 'Botafogo');
insert into team(id, name) values(126, 'Reading');
insert into team(id, name) values(127, 'Rayo Vallecano De Madrid SAD');
insert into team(id, name) values(128, 'RCD Espanyol De Barcelona SAD');
insert into team(id, name) values(129, 'Bradford City');
insert into team(id, name) values(130, 'Cardiff City');
insert into team(id, name) values(131, 'Vasco Da Gama');
insert into team(id, name) values(132, 'FC Basel');
insert into team(id, name) values(133, 'Middlesbrough');
insert into team(id, name) values(134, 'TSV  München');
insert into team(id, name) values(135, 'Dinamo Moskva');
insert into team(id, name) values(136, 'SpVgg Greuther Fürth');
insert into team(id, name) values(137, 'Fortuna Düsseldorf');
insert into team(id, name) values(138, 'FC Red Bull Salzburg');
insert into team(id, name) values(139, 'Sc Heerenveen');
insert into team(id, name) values(140, 'Levante Unión Deportiva SAD');
insert into team(id, name) values(141, 'Sheffield United');
insert into team(id, name) values(142, 'SC Freiburg');
insert into team(id, name) values(143, 'UNAM');
insert into team(id, name) values(144, 'KRC Genk');
insert into team(id, name) values(145, 'Getafe Club De Fútbol SAD');
insert into team(id, name) values(146, 'Tigres UANL');
insert into team(id, name) values(147, 'FC Sochaux-Montbéliard');
insert into team(id, name) values(148, 'SC Braga');
insert into team(id, name) values(149, 'AEK Athens');
insert into team(id, name) values(150, 'Real Club Deportivo Mallorca SAD');
insert into team(id, name) values(151, 'Panathinaikos FC');
insert into team(id, name) values(152, 'Blackpool');
insert into team(id, name) values(153, 'Barnet');
insert into team(id, name) values(154, 'Real Zaragoza SAD');
insert into team(id, name) values(155, 'Chievo Verona');
insert into team(id, name) values(156, 'Derby County');
insert into team(id, name) values(157, 'Lokomotiv Moskva');
insert into team(id, name) values(158, 'Club Brugge KV');
insert into team(id, name) values(159, 'Molde FK');
insert into team(id, name) values(160, 'Seattle Sounders FC');
insert into team(id, name) values(161, 'L Warszawa');
insert into team(id, name) values(162, 'Hull City');
insert into team(id, name) values(163, 'Racing Club De Lens');
insert into team(id, name) values(164, 'FC Lorient Bretagne Sud');
insert into team(id, name) values(165, 'FC København');
insert into team(id, name) values(166, 'Brighton & Hove Albion');
insert into team(id, name) values(167, 'Plymouth Argyle');
insert into team(id, name) values(168, 'Millwall');
insert into team(id, name) values(169, 'Real Club Celta De Vigo SAD');
insert into team(id, name) values(170, 'Sporting Club Bastia');
insert into team(id, name) values(171, 'VfL Bochum');
insert into team(id, name) values(172, 'FC Augsburg');
insert into team(id, name) values(173, 'L Poznań');
insert into team(id, name) values(174, 'Club Atlético Osasuna');
insert into team(id, name) values(175, 'Cruz Azul');
insert into team(id, name) values(176, 'Crewe Alexandra');
insert into team(id, name) values(177, 'FC Nantes');
insert into team(id, name) values(178, 'Djurgårdens IF');
insert into team(id, name) values(179, 'Siena');
insert into team(id, name) values(180, 'Ipswich Town');
insert into team(id, name) values(181, 'Monterrey');
insert into team(id, name) values(182, 'Unión Deportiva Almería SAD');
insert into team(id, name) values(183, 'Real Valladolid Club De Fútbol SAD');
insert into team(id, name) values(184, 'FC Kaiserslautern');
insert into team(id, name) values(185, 'Fleetwood Town');
insert into team(id, name) values(186, 'AC Ajaccio');
insert into team(id, name) values(187, 'AS Nancy Lorraine');
insert into team(id, name) values(188, 'Atlas');
insert into team(id, name) values(189, 'IFK Göteborg');
insert into team(id, name) values(190, 'AJ Auxerre');
insert into team(id, name) values(191, 'Kaizer Chiefs');
insert into team(id, name) values(192, 'FC Zürich');
insert into team(id, name) values(193, 'FC Utrecht');
insert into team(id, name) values(194, 'SK Rapid Wien');
insert into team(id, name) values(195, 'Doncaster Rovers');
insert into team(id, name) values(196, 'Rotherham United');
insert into team(id, name) values(197, 'W Kraków');
insert into team(id, name) values(198, 'Sheffield Wednesday');
insert into team(id, name) values(199, 'Pachuca');
insert into team(id, name) values(200, 'Charlton Athletic');
insert into team(id, name) values(201, 'Malmö FF');
insert into team(id, name) values(202, 'Empoli');
insert into team(id, name) values(203, 'FK Austria Wien');
insert into team(id, name) values(204, 'Grasshopper-Club');
insert into team(id, name) values(205, 'Bristol Rovers');
insert into team(id, name) values(206, 'Santos Laguna');
insert into team(id, name) values(207, 'Stade Malherbe Caen');
insert into team(id, name) values(208, 'FC Seoul');
insert into team(id, name) values(209, 'Hércules Club De Fútbol SAD');
insert into team(id, name) values(210, 'Sassuolo');
insert into team(id, name) values(211, 'MSV Duisburg');
insert into team(id, name) values(212, 'PAOK');
insert into team(id, name) values(213, 'Valenciennes FC');
insert into team(id, name) values(214, 'FC St Pauli');
insert into team(id, name) values(215, 'Bari');
insert into team(id, name) values(216, 'Hellas Verona');
insert into team(id, name) values(217, 'KAA Gent');
insert into team(id, name) values(218, 'Coventry City');
insert into team(id, name) values(219, 'SV Zulte-Waregem');
insert into team(id, name) values(220, 'Sydney FC');
insert into team(id, name) values(221, 'Peterborough United');
insert into team(id, name) values(222, 'FC Groningen');
insert into team(id, name) values(223, 'Energie Cottbus');
insert into team(id, name) values(224, 'Orlando Pirates');
insert into team(id, name) values(225, 'Vitória De Setúbal');
insert into team(id, name) values(226, 'Shrewsbury');
insert into team(id, name) values(227, 'Académica Coimbra');
insert into team(id, name) values(228, 'Burnley');
insert into team(id, name) values(229, 'Brøndby IF');
insert into team(id, name) values(230, 'FC Sion');
insert into team(id, name) values(231, 'Coritiba');
insert into team(id, name) values(232, 'Bournemouth');
insert into team(id, name) values(233, 'Barnsley');
insert into team(id, name) values(234, 'Granada Club De Fútbol');
insert into team(id, name) values(235, 'DC United');
insert into team(id, name) values(236, 'Real Sporting De Gijón SAD');
insert into team(id, name) values(237, 'Atlante');
insert into team(id, name) values(238, 'Vancouver Whitecaps FC');
insert into team(id, name) values(239, 'ES Troyes AC');
insert into team(id, name) values(240, 'C Funchal');
insert into team(id, name) values(241, 'Vitória De Guimarães');
insert into team(id, name) values(242, 'Rosenborg BK');
insert into team(id, name) values(243, 'Northampton Town');
insert into team(id, name) values(244, 'Monarcas Morelia');
insert into team(id, name) values(245, 'Paços Ferreira');
insert into team(id, name) values(246, 'Stade Brestois');
insert into team(id, name) values(247, 'Tromsø IL');
insert into team(id, name) values(248, 'Reggina');
insert into team(id, name) values(249, 'Bristol City');
insert into team(id, name) values(250, 'Gillingham');
insert into team(id, name) values(251, 'ADO Den Haag');
insert into team(id, name) values(252, 'FC Nordsjælland');
insert into team(id, name) values(253, 'Vercelli');
insert into team(id, name) values(254, 'Lillestrøm SK');
insert into team(id, name) values(255, 'BSC Young Boys');
insert into team(id, name) values(256, 'Racing Club');
insert into team(id, name) values(257, 'Club Deportivo Chivas USA');
insert into team(id, name) values(258, 'Le Mans FC');
insert into team(id, name) values(259, 'Stade De Reims');
insert into team(id, name) values(260, 'Heart Of Midlothian');
insert into team(id, name) values(261, 'AFC Wimbledon');
insert into team(id, name) values(262, 'Notts County');
insert into team(id, name) values(263, 'Rio Ave FC');
insert into team(id, name) values(264, 'Eintracht Braunschweig');
insert into team(id, name) values(265, 'Columbus Crew');
insert into team(id, name) values(266, 'Cesena');
insert into team(id, name) values(267, 'Oldham Athletic');
insert into team(id, name) values(268, 'Suwon Samsung Bluewings');
insert into team(id, name) values(269, 'Le Havre Athletic Club');
insert into team(id, name) values(270, 'Swindon Town');
insert into team(id, name) values(271, 'Chicago Fire');
insert into team(id, name) values(272, 'Chesterfield');
insert into team(id, name) values(273, 'Dundee United');
insert into team(id, name) values(274, 'Port Vale');
insert into team(id, name) values(275, 'Tijuana');
insert into team(id, name) values(276, 'Padua');
insert into team(id, name) values(277, 'Evian Thonon Gaillard FC');
insert into team(id, name) values(278, 'Colorado Rapids');
insert into team(id, name) values(279, 'Vålerenga Fotball');
insert into team(id, name) values(280, 'Exeter City');
insert into team(id, name) values(281, 'Real Racing Club SAD');
insert into team(id, name) values(282, 'Unión Deportiva Las Palmas SAD');
insert into team(id, name) values(283, 'AIK Fotboll');
insert into team(id, name) values(284, 'Milton Keynes Dons');
insert into team(id, name) values(285, 'SK Sturm Graz');
insert into team(id, name) values(286, 'Livorno');
insert into team(id, name) values(287, 'Elche Club De Fútbol SAD');
insert into team(id, name) values(288, 'Accrington Stanley');
insert into team(id, name) values(289, 'SV Josko Ried');
insert into team(id, name) values(290, 'Toluca');
insert into team(id, name) values(291, 'Ascoli');
insert into team(id, name) values(292, 'York City');
insert into team(id, name) values(293, 'New England Revolution');
insert into team(id, name) values(294, 'Sporting Kansas City');
insert into team(id, name) values(295, 'Royal Charleroi SC');
insert into team(id, name) values(296, 'Oxford United FC');
insert into team(id, name) values(297, 'San Luis');
insert into team(id, name) values(298, 'Dijon FCO');
insert into team(id, name) values(299, 'SK Brann');
insert into team(id, name) values(300, 'Córdoba Club De Fútbol SAD');
insert into team(id, name) values(301, 'Bahia');
insert into team(id, name) values(302, 'FC Dallas');
insert into team(id, name) values(303, 'Terek Grozny');
insert into team(id, name) values(304, 'Southend United');
insert into team(id, name) values(305, 'Jaguares De Chiapas');
insert into team(id, name) values(306, 'KSV Cercle Brugge');
insert into team(id, name) values(307, 'Vicenza');
insert into team(id, name) values(308, 'Roda JC');
insert into team(id, name) values(309, 'Helsingborgs IF');
insert into team(id, name) values(310, 'P Warszawa');
insert into team(id, name) values(311, 'FC Union Berlin');
insert into team(id, name) values(312, 'Shamrock Rovers');
insert into team(id, name) values(313, 'Querétaro');
insert into team(id, name) values(314, 'Angers SCO');
insert into team(id, name) values(315, 'Lierse SK');
insert into team(id, name) values(316, 'NEC');
insert into team(id, name) values(317, 'Aldershot Town');
insert into team(id, name) values(318, 'Preston North End');
insert into team(id, name) values(319, 'Huddersfield Town');
insert into team(id, name) values(320, 'Toronto FC');
insert into team(id, name) values(321, 'Rochdale');
insert into team(id, name) values(322, 'NAC Breda');
insert into team(id, name) values(323, 'Wycombe Wanderers');
insert into team(id, name) values(324, 'FSV Frankfurt');
insert into team(id, name) values(325, 'Beerschot AC');
insert into team(id, name) values(326, 'N Recife');
insert into team(id, name) values(327, 'Kuban Krasnodar');
insert into team(id, name) values(328, 'Viking FK');
insert into team(id, name) values(329, 'CD Nacional');
insert into team(id, name) values(330, 'En Avant De Guingamp');
insert into team(id, name) values(331, 'Aberdeen');
insert into team(id, name) values(332, 'Modena');
insert into team(id, name) values(333, 'SC Paderborn');
insert into team(id, name) values(334, 'Leyton Orient');
insert into team(id, name) values(335, 'Jeonbuk Hyundai Motors');
insert into team(id, name) values(336, 'Krylya Sovetov Samara');
insert into team(id, name) values(337, 'Heracles Almelo');
insert into team(id, name) values(338, 'Strømsgodset IF');
insert into team(id, name) values(339, 'G Bełchatów');
insert into team(id, name) values(340, 'RC Recreativo');
insert into team(id, name) values(341, 'La Berrichonne De Châteauroux');
insert into team(id, name) values(342, 'Santa Catarina');
insert into team(id, name) values(343, 'Sporting Lokeren OV');
insert into team(id, name) values(344, 'VVV-Venlo');
insert into team(id, name) values(345, 'Central Coast Mariners FC');
insert into team(id, name) values(346, 'Houston Dynamo');
insert into team(id, name) values(347, 'G Zabrze');
insert into team(id, name) values(348, 'Brentford');
insert into team(id, name) values(349, 'Walsall');
insert into team(id, name) values(350, 'Al-Hilal Saudi FC');
insert into team(id, name) values(351, 'Melbourne Victory FC');
insert into team(id, name) values(352, 'Yeovil Town');
insert into team(id, name) values(353, 'Ponte Preta');
insert into team(id, name) values(354, 'Novara');
insert into team(id, name) values(355, 'Xerez Club Deportivo SAD');
insert into team(id, name) values(356, 'Dynamo Dresden');
insert into team(id, name) values(357, 'Willem II');
insert into team(id, name) values(358, 'Lanciano');
insert into team(id, name) values(359, 'Dagenham And Redbridge');
insert into team(id, name) values(360, 'Grosseto');
insert into team(id, name) values(361, 'Cheltenham Town');
insert into team(id, name) values(362, 'Real Salt Lake');
insert into team(id, name) values(363, 'Morecambe');
insert into team(id, name) values(364, 'Motherwell');
insert into team(id, name) values(365, 'BK Häcken');
insert into team(id, name) values(366, 'Torquay United');
insert into team(id, name) values(367, 'Castellammare Di Stabia');
insert into team(id, name) values(368, 'CS Sedan Ardennes');
insert into team(id, name) values(369, 'Club Deportivo Numancia De Soria SAD');
insert into team(id, name) values(370, 'Hibernian');
insert into team(id, name) values(371, 'Montreal Impact');
insert into team(id, name) values(372, 'Örebro SK');
insert into team(id, name) values(373, 'Burton Albion');
insert into team(id, name) values(374, 'IF Elfsborg');
insert into team(id, name) values(375, 'San Jose Earthquakes');
insert into team(id, name) values(376, 'A Goiânia');
insert into team(id, name) values(377, 'Stabæk Fotball');
insert into team(id, name) values(378, 'FC St Gallen');
insert into team(id, name) values(379, 'Wrocław');
insert into team(id, name) values(380, 'RKC Waalwijk');
insert into team(id, name) values(381, 'Nîmes Olympique');
insert into team(id, name) values(382, 'FC Ingolstadt');
insert into team(id, name) values(383, 'SV Mattersburg');
insert into team(id, name) values(384, 'J Białystok');
insert into team(id, name) values(385, 'Odense Boldklub');
insert into team(id, name) values(386, 'Adelaide United');
insert into team(id, name) values(387, 'KV Mechelen');
insert into team(id, name) values(388, 'Lubin');
insert into team(id, name) values(389, 'FC Erzgebirge Aue');
insert into team(id, name) values(390, 'W Łódź');
insert into team(id, name) values(391, 'Bohemians FC');
insert into team(id, name) values(392, 'Puebla');
insert into team(id, name) values(393, 'Real Murcia CF');
insert into team(id, name) values(394, 'UCD AFC');
insert into team(id, name) values(395, 'AC Arles Avignon');
insert into team(id, name) values(396, 'Ulsan Hyundai Horang-I');
insert into team(id, name) values(397, 'Bury');
insert into team(id, name) values(398, 'Cittadella');
insert into team(id, name) values(399, 'Newcastle United Jets FC');
insert into team(id, name) values(400, 'Carlisle United');
insert into team(id, name) values(401, 'FC Luzern');
insert into team(id, name) values(402, 'FC Rostov');
insert into team(id, name) values(403, 'Gdańsk');
insert into team(id, name) values(404, 'Colchester United');
insert into team(id, name) values(405, 'R Chorzów');
insert into team(id, name) values(406, 'Wellington Phoenix');
insert into team(id, name) values(407, 'FC Wacker Innsbruck');
insert into team(id, name) values(408, 'Philadelphia Union');
insert into team(id, name) values(409, 'Kilmarnock');
insert into team(id, name) values(410, 'Scunthorpe United');
insert into team(id, name) values(411, 'Brisbane Roar Football Club');
insert into team(id, name) values(412, 'Aalesunds FK');
insert into team(id, name) values(413, 'Spezia');
insert into team(id, name) values(414, 'Aalborg BK');
insert into team(id, name) values(415, 'Portland Timbers');
insert into team(id, name) values(416, 'Al-Shabab');
insert into team(id, name) values(417, 'KV Kortrijk');
insert into team(id, name) values(418, 'FC Istres Ouest Provence');
insert into team(id, name) values(419, 'FC Midtjylland');
insert into team(id, name) values(420, 'SC Beira Mar');
insert into team(id, name) values(421, 'Tranmere Rovers');
insert into team(id, name) values(422, 'Crotone');
insert into team(id, name) values(423, 'Alaniya Vladikavkaz');
insert into team(id, name) values(424, 'Bray Wanderers');
insert into team(id, name) values(425, 'Amkar Perm');
insert into team(id, name) values(426, 'Hartlepool United');
insert into team(id, name) values(427, 'Tours FC');
insert into team(id, name) values(428, 'Crawley Town');
insert into team(id, name) values(429, 'Sociedad Deportiva Huesca SAD');
insert into team(id, name) values(430, 'SC Olhanense');
insert into team(id, name) values(431, 'Portuguesa');
insert into team(id, name) values(432, 'Girona Fútbol Club SAD');
insert into team(id, name) values(433, 'Agrupación Deportiva Alcorcón');
insert into team(id, name) values(434, 'St Mirren');
insert into team(id, name) values(435, 'Club León');
insert into team(id, name) values(436, 'Kalmar FF');
insert into team(id, name) values(437, 'Al-Ahli Saudi FC');
insert into team(id, name) values(438, 'RAEC Mons');
insert into team(id, name) values(439, 'S Recife');
insert into team(id, name) values(440, 'Pogoń Szczecin');
insert into team(id, name) values(441, 'Daegu FC');
insert into team(id, name) values(442, 'SangJu Sangmu Phoenix FC');
insert into team(id, name) values(443, 'Esbjerg FB');
insert into team(id, name) values(444, 'Seongnam Ilhwa Chunma');
insert into team(id, name) values(445, 'Inverness Caledonian Thistle');
insert into team(id, name) values(446, 'Bielsko-Biała');
insert into team(id, name) values(447, 'Varese');
insert into team(id, name) values(448, 'Perth Glory FC');
insert into team(id, name) values(449, 'St Patrick''s Athletic');
insert into team(id, name) values(450, 'Daejeon Citizen');
insert into team(id, name) values(451, 'Clermont Foot Auvergne');
insert into team(id, name) values(452, 'Servette FC');
insert into team(id, name) values(453, 'Stade Lavallois Mayenne FC');
insert into team(id, name) values(454, 'AC Horsens');
insert into team(id, name) values(455, 'Jeju United FC');
insert into team(id, name) values(456, 'Sligo Rovers');
insert into team(id, name) values(457, 'Western Sydney Wanderers FC');
insert into team(id, name) values(458, 'SønderjyskE');
insert into team(id, name) values(459, 'FC Trenkwalder Admira');
insert into team(id, name) values(460, 'GAIS');
insert into team(id, name) values(461, 'Chunnam Dragons');
insert into team(id, name) values(462, 'FC Krasnodar');
insert into team(id, name) values(463, 'FC Lausanne-Sports');
insert into team(id, name) values(464, 'Ittihad FC');
insert into team(id, name) values(465, 'Stevenage');
insert into team(id, name) values(466, 'Busan I''Park');
insert into team(id, name) values(467, 'Aarhus GF');
insert into team(id, name) values(468, 'Sociedad Deportiva Ponferradina SAD');
insert into team(id, name) values(469, 'Terni');
insert into team(id, name) values(470, 'Moreira De Cónegos');
insert into team(id, name) values(471, 'Mjällby AIF');
insert into team(id, name) values(472, 'GyeongNam FC');
insert into team(id, name) values(473, 'Pohang Steelers');
insert into team(id, name) values(474, 'Kielce');
insert into team(id, name) values(475, 'Volga Nizhny Novgorod');
insert into team(id, name) values(476, 'Fredrikstad FK');
insert into team(id, name) values(477, 'SSV Jahn Regensburg');
insert into team(id, name) values(478, 'Derry City');
insert into team(id, name) values(479, 'V Barcelos');
insert into team(id, name) values(480, 'St Johnstone FC');
insert into team(id, name) values(481, 'Club Deportivo Guadalajara');
insert into team(id, name) values(482, 'CE Sabadell FC');
insert into team(id, name) values(483, 'FC Thun');
insert into team(id, name) values(484, 'Incheon United FC');
insert into team(id, name) values(485, 'PEC Zwolle');
insert into team(id, name) values(486, 'Chamois Niortais FC');
insert into team(id, name) values(487, 'Randers FC');
insert into team(id, name) values(488, 'IFK Norrkoping');
insert into team(id, name) values(489, 'Drogheda United');
insert into team(id, name) values(490, 'Gefle IF');
insert into team(id, name) values(491, 'Dundalk');
insert into team(id, name) values(492, 'Club Deportivo Mirandés');
insert into team(id, name) values(493, 'Melbourne Heart FC');
insert into team(id, name) values(494, 'SC Wiener Neustadt');
insert into team(id, name) values(495, 'VfR Aalen');
insert into team(id, name) values(496, 'Odd Grenland');
insert into team(id, name) values(497, 'SV Sandhausen');
insert into team(id, name) values(498, 'Hønefoss BK');
insert into team(id, name) values(499, 'Cork City');
insert into team(id, name) values(500, 'Oud-Heverlee Leuven');
insert into team(id, name) values(501, 'Estoril');
insert into team(id, name) values(502, 'Silkeborg IF');
insert into team(id, name) values(503, 'Gazélec FC Ajaccio');
insert into team(id, name) values(504, 'Waasland-Beveren');
insert into team(id, name) values(505, 'FK Haugesund');
insert into team(id, name) values(506, 'Åtvidabergs FF');
insert into team(id, name) values(507, 'Al Nassr FC');
insert into team(id, name) values(508, 'Gangwon FC');
insert into team(id, name) values(509, 'Club Deportivo Lugo');
insert into team(id, name) values(510, 'Mordovia Saransk');
insert into team(id, name) values(511, 'Al-Raed FC');
insert into team(id, name) values(512, 'Al Wehdah Club');
insert into team(id, name) values(513, 'Piast Gliwice');
insert into team(id, name) values(514, 'Wolfsberger AC');
insert into team(id, name) values(515, 'Syrianska');
insert into team(id, name) values(516, 'Alshoulla FC');
insert into team(id, name) values(517, 'Al-Faisaly FC');
insert into team(id, name) values(518, 'Dundee FC');
insert into team(id, name) values(519, 'Al-Fateh FC');
insert into team(id, name) values(520, 'Ross County FC');
insert into team(id, name) values(521, 'Hajer FC');
insert into team(id, name) values(522, 'GIF Sundsvall');
insert into team(id, name) values(523, 'GwangJu FC');
insert into team(id, name) values(524, 'Al-Taawoun FC');
insert into team(id, name) values(525, 'Ettifaq FC');
insert into team(id, name) values(526, 'Sandnes Ulf');
insert into team(id, name) values(527, 'Shelbourne FC');
insert into team(id, name) values(528, 'Najran FC');
insert into team(id, name) values(529, 'Sogndal');
insert into team(id, name) values(530, 'Argentina');
insert into team(id, name) values(531, 'Australia');
insert into team(id, name) values(532, 'Austria');
insert into team(id, name) values(533, 'Belgium');
insert into team(id, name) values(534, 'Bolivia');
insert into team(id, name) values(535, 'Brazil');
insert into team(id, name) values(536, 'Bulgaria');
insert into team(id, name) values(537, 'Camaroon');
insert into team(id, name) values(538, 'Chile');
insert into team(id, name) values(539, 'Colombia');
insert into team(id, name) values(540, 'Côte d’Ivoire');
insert into team(id, name) values(541, 'Czech Republic');
insert into team(id, name) values(542, 'Denmark');
insert into team(id, name) values(543, 'Ecuador');
insert into team(id, name) values(544, 'Egypt');
insert into team(id, name) values(545, 'England');
insert into team(id, name) values(546, 'Finland');
insert into team(id, name) values(547, 'France');
insert into team(id, name) values(548, 'Germany');
insert into team(id, name) values(549, 'Greece');
insert into team(id, name) values(550, 'Hungary');
insert into team(id, name) values(551, 'India');
insert into team(id, name) values(552, 'Ireland');
insert into team(id, name) values(553, 'Italy');
insert into team(id, name) values(554, 'Korea Republic');
insert into team(id, name) values(555, 'Mexico');
insert into team(id, name) values(556, 'Netherlands');
insert into team(id, name) values(557, 'New Zealand');
insert into team(id, name) values(558, 'Northern Ireland');
insert into team(id, name) values(559, 'Norway');
insert into team(id, name) values(560, 'Paraguay');
insert into team(id, name) values(561, 'Peru');
insert into team(id, name) values(562, 'Poland P');
insert into team(id, name) values(563, 'ortugal');
insert into team(id, name) values(564, 'Romania Russia');
insert into team(id, name) values(565, 'Scotland');
insert into team(id, name) values(566, 'Slovenia');
insert into team(id, name) values(567, 'South Africa');
insert into team(id, name) values(568, 'Spain');
insert into team(id, name) values(569, 'Sweden');
insert into team(id, name) values(570, 'Switzerland');
insert into team(id, name) values(571, 'Turkey');
insert into team(id, name) values(572, 'United States');
insert into team(id, name) values(573, 'Uruguay');
insert into team(id, name) values(574, 'Venezuela');



# --- !Downs
SET REFERENTIAL_INTEGRITY FALSE;

delete from team;

SET REFERENTIAL_INTEGRITY TRUE;
