# --- Just test data

# --- !Ups
insert into player values (1, 'Bruce Grannec');
insert into player values (2, 'Alfonso Ramos');

insert into record values (1, 82, 11, 4, 192, 68, 1);

insert into record values (2, 65, 15, 3, 224, 81, 2);

insert into team(name) values('Real Madrid Club De Fútbol');
insert into team(name) values('FC Barcelona');
insert into team(name) values('Arsenal');
insert into team(name) values('Milan');
insert into team(name) values('Manchester United');
insert into team(name) values('Borussia Dortmund');
insert into team(name) values('Chelsea');
insert into team(name) values('Juventus');
insert into team(name) values('Liverpool');
insert into team(name) values('Bayern München');
insert into team(name) values('Manchester City');
insert into team(name) values('Paris Saint-Germain');
insert into team(name) values('Tottenham Hotspur');
insert into team(name) values('Inter');
insert into team(name) values('Galatasaray SK');
insert into team(name) values('Club Atlético De Madrid SAD');
insert into team(name) values('Newcastle United');
insert into team(name) values('Roma');
insert into team(name) values('FC Porto');
insert into team(name) values('FC Schalke');
insert into team(name) values('Ajax');
insert into team(name) values('Málaga Club De Fútbol SAD');
insert into team(name) values('Napoli');
insert into team(name) values('Everton');
insert into team(name) values('Olympique Lyonnais');
insert into team(name) values('Valencia Club De Fútbol SAD');
insert into team(name) values('Aston Villa');
insert into team(name) values('ACF Fiorentina');
insert into team(name) values('Sport Lisboa Benfica');
insert into team(name) values('Queens Park Rangers');
insert into team(name) values('Southampton');
insert into team(name) values('Santos');
insert into team(name) values('Fútbol Club Barcelona “B”');
insert into team(name) values('Lazio');
insert into team(name) values('Swansea City');
insert into team(name) values('VfL Wolfsburg');
insert into team(name) values('Feyenoord');
insert into team(name) values('Corinthians');
insert into team(name) values('Anzhi Makhachkala');
insert into team(name) values('Sporting CP');
insert into team(name) values('Olympique De Marseille');
insert into team(name) values('Hamburger SV');
insert into team(name) values('Bayer  Leverkusen');
insert into team(name) values('AS Saint-Etienne');
insert into team(name) values('Borussia M''gladbach');
insert into team(name) values('PSV');
insert into team(name) values('São Paulo');
insert into team(name) values('Werder Bremen');
insert into team(name) values('LOSC Lille Métropole');
insert into team(name) values('Athletic Club De Bilbao');
insert into team(name) values('CSKA Moskva');
insert into team(name) values('Udinese');
insert into team(name) values('Zenit St Petersburg');
insert into team(name) values('Sevilla Fútbol Club SAD');
insert into team(name) values('West Ham United');
insert into team(name) values('Fulham');
insert into team(name) values('Celtic');
insert into team(name) values('Villarreal Club De Fútbol SAD');
insert into team(name) values('Sunderland');
insert into team(name) values('Spartak Moskva');
insert into team(name) values('Atlético Mineiro');
insert into team(name) values('AS Monaco FC');
insert into team(name) values('Flamengo');
insert into team(name) values('Real Sociedad De Fútbol SAD');
insert into team(name) values('Real Madrid Castilla');
insert into team(name) values('Wigan Athletic');
insert into team(name) values('West Bromwich Albion');
insert into team(name) values('Grêmio');
insert into team(name) values('River Plate');
insert into team(name) values('Sampdoria');
insert into team(name) values('Genoa');
insert into team(name) values('Palermo');
insert into team(name) values('Blackburn Rovers');
insert into team(name) values('Stoke City');
insert into team(name) values('RSC Anderlecht');
insert into team(name) values('Bolton Wanderers');
insert into team(name) values('América');
insert into team(name) values('Hannover');
insert into team(name) values('Real Club Deportivo De La Coruña SAD');
insert into team(name) values('F Torino');
insert into team(name) values('Fluminense');
insert into team(name) values('Norwich City');
insert into team(name) values('VfB Stuttgart');
insert into team(name) values('Leeds United');
insert into team(name) values('FC Nürnberg');
insert into team(name) values('Boca Juniors');
insert into team(name) values('Girondins De Bordeaux');
insert into team(name) values('Internacional');
insert into team(name) values('Vitesse');
insert into team(name) values('Parma');
insert into team(name) values('Real Betis Balompié SAD');
insert into team(name) values('Los Angeles Galaxy');
insert into team(name) values('Crystal Palace');
insert into team(name) values('Standard De Liège');
insert into team(name) values('Toulouse FC');
insert into team(name) values('AZ Alkmaar');
insert into team(name) values('Cagliari');
insert into team(name) values('Birmingham City');
insert into team(name) values('Bologna');
insert into team(name) values('Eintracht Frankfurt');
insert into team(name) values('Atalanta');
insert into team(name) values('Rangers');
insert into team(name) values('Montpellier Hérault Sport Club');
insert into team(name) values('Guadalajara');
insert into team(name) values('OGC Nice');
insert into team(name) values('Palmeiras');
insert into team(name) values('Brescia');
insert into team(name) values('Cruzeiro');
insert into team(name) values('Watford');
insert into team(name) values('New York Red Bulls');
insert into team(name) values('Stade Rennais FC');
insert into team(name) values('Rubin Kazan');
insert into team(name) values('Olympiakos CFP');
insert into team(name) values('Catania');
insert into team(name) values('FC Twente');
insert into team(name) values('Hertha BSC');
insert into team(name) values('Wolverhampton Wanderers');
insert into team(name) values('FC Köln');
insert into team(name) values('Leicester City');
insert into team(name) values('TSG  Hoffenheim');
insert into team(name) values('Nottingham Forest');
insert into team(name) values('Pescara');
insert into team(name) values('FSV Mainz');
insert into team(name) values('Portsmouth');
insert into team(name) values('Botafogo');
insert into team(name) values('Reading');
insert into team(name) values('Rayo Vallecano De Madrid SAD');
insert into team(name) values('RCD Espanyol De Barcelona SAD');
insert into team(name) values('Bradford City');
insert into team(name) values('Cardiff City');
insert into team(name) values('Vasco Da Gama');
insert into team(name) values('FC Basel');
insert into team(name) values('Middlesbrough');
insert into team(name) values('TSV  München');
insert into team(name) values('Dinamo Moskva');
insert into team(name) values('SpVgg Greuther Fürth');
insert into team(name) values('Fortuna Düsseldorf');
insert into team(name) values('FC Red Bull Salzburg');
insert into team(name) values('Sc Heerenveen');
insert into team(name) values('Levante Unión Deportiva SAD');
insert into team(name) values('Sheffield United');
insert into team(name) values('SC Freiburg');
insert into team(name) values('UNAM');
insert into team(name) values('KRC Genk');
insert into team(name) values('Getafe Club De Fútbol SAD');
insert into team(name) values('Tigres UANL');
insert into team(name) values('FC Sochaux-Montbéliard');
insert into team(name) values('SC Braga');
insert into team(name) values('AEK Athens');
insert into team(name) values('Real Club Deportivo Mallorca SAD');
insert into team(name) values('Panathinaikos FC');
insert into team(name) values('Blackpool');
insert into team(name) values('Barnet');
insert into team(name) values('Real Zaragoza SAD');
insert into team(name) values('Chievo Verona');
insert into team(name) values('Derby County');
insert into team(name) values('Lokomotiv Moskva');
insert into team(name) values('Club Brugge KV');
insert into team(name) values('Molde FK');
insert into team(name) values('Seattle Sounders FC');
insert into team(name) values('L Warszawa');
insert into team(name) values('Hull City');
insert into team(name) values('Racing Club De Lens');
insert into team(name) values('FC Lorient Bretagne Sud');
insert into team(name) values('FC København');
insert into team(name) values('Brighton & Hove Albion');
insert into team(name) values('Plymouth Argyle');
insert into team(name) values('Millwall');
insert into team(name) values('Real Club Celta De Vigo SAD');
insert into team(name) values('Sporting Club Bastia');
insert into team(name) values('VfL Bochum');
insert into team(name) values('FC Augsburg');
insert into team(name) values('L Poznań');
insert into team(name) values('Club Atlético Osasuna');
insert into team(name) values('Cruz Azul');
insert into team(name) values('Crewe Alexandra');
insert into team(name) values('FC Nantes');
insert into team(name) values('Djurgårdens IF');
insert into team(name) values('Siena');
insert into team(name) values('Ipswich Town');
insert into team(name) values('Monterrey');
insert into team(name) values('Unión Deportiva Almería SAD');
insert into team(name) values('Real Valladolid Club De Fútbol SAD');
insert into team(name) values('FC Kaiserslautern');
insert into team(name) values('Fleetwood Town');
insert into team(name) values('AC Ajaccio');
insert into team(name) values('AS Nancy Lorraine');
insert into team(name) values('Atlas');
insert into team(name) values('IFK Göteborg');
insert into team(name) values('AJ Auxerre');
insert into team(name) values('Kaizer Chiefs');
insert into team(name) values('FC Zürich');
insert into team(name) values('FC Utrecht');
insert into team(name) values('SK Rapid Wien');
insert into team(name) values('Doncaster Rovers');
insert into team(name) values('Rotherham United');
insert into team(name) values('W Kraków');
insert into team(name) values('Sheffield Wednesday');
insert into team(name) values('Pachuca');
insert into team(name) values('Charlton Athletic');
insert into team(name) values('Malmö FF');
insert into team(name) values('Empoli');
insert into team(name) values('FK Austria Wien');
insert into team(name) values('Grasshopper-Club');
insert into team(name) values('Bristol Rovers');
insert into team(name) values('Santos Laguna');
insert into team(name) values('Stade Malherbe Caen');
insert into team(name) values('FC Seoul');
insert into team(name) values('Hércules Club De Fútbol SAD');
insert into team(name) values('Sassuolo');
insert into team(name) values('MSV Duisburg');
insert into team(name) values('PAOK');
insert into team(name) values('Valenciennes FC');
insert into team(name) values('FC St Pauli');
insert into team(name) values('Bari');
insert into team(name) values('Hellas Verona');
insert into team(name) values('KAA Gent');
insert into team(name) values('Coventry City');
insert into team(name) values('SV Zulte-Waregem');
insert into team(name) values('Sydney FC');
insert into team(name) values('Peterborough United');
insert into team(name) values('FC Groningen');
insert into team(name) values('Energie Cottbus');
insert into team(name) values('Orlando Pirates');
insert into team(name) values('Vitória De Setúbal');
insert into team(name) values('Shrewsbury');
insert into team(name) values('Académica Coimbra');
insert into team(name) values('Burnley');
insert into team(name) values('Brøndby IF');
insert into team(name) values('FC Sion');
insert into team(name) values('Coritiba');
insert into team(name) values('Bournemouth');
insert into team(name) values('Barnsley');
insert into team(name) values('Granada Club De Fútbol');
insert into team(name) values('DC United');
insert into team(name) values('Real Sporting De Gijón SAD');
insert into team(name) values('Atlante');
insert into team(name) values('Vancouver Whitecaps FC');
insert into team(name) values('ES Troyes AC');
insert into team(name) values('C Funchal');
insert into team(name) values('Vitória De Guimarães');
insert into team(name) values('Rosenborg BK');
insert into team(name) values('Northampton Town');
insert into team(name) values('Monarcas Morelia');
insert into team(name) values('Paços Ferreira');
insert into team(name) values('Stade Brestois');
insert into team(name) values('Tromsø IL');
insert into team(name) values('Reggina');
insert into team(name) values('Bristol City');
insert into team(name) values('Gillingham');
insert into team(name) values('ADO Den Haag');
insert into team(name) values('FC Nordsjælland');
insert into team(name) values('Vercelli');
insert into team(name) values('Lillestrøm SK');
insert into team(name) values('BSC Young Boys');
insert into team(name) values('Racing Club');
insert into team(name) values('Club Deportivo Chivas USA');
insert into team(name) values('Le Mans FC');
insert into team(name) values('Stade De Reims');
insert into team(name) values('Heart Of Midlothian');
insert into team(name) values('AFC Wimbledon');
insert into team(name) values('Notts County');
insert into team(name) values('Rio Ave FC');
insert into team(name) values('Eintracht Braunschweig');
insert into team(name) values('Columbus Crew');
insert into team(name) values('Cesena');
insert into team(name) values('Oldham Athletic');
insert into team(name) values('Suwon Samsung Bluewings');
insert into team(name) values('Le Havre Athletic Club');
insert into team(name) values('Swindon Town');
insert into team(name) values('Chicago Fire');
insert into team(name) values('Chesterfield');
insert into team(name) values('Dundee United');
insert into team(name) values('Port Vale');
insert into team(name) values('Tijuana');
insert into team(name) values('Padua');
insert into team(name) values('Evian Thonon Gaillard FC');
insert into team(name) values('Colorado Rapids');
insert into team(name) values('Vålerenga Fotball');
insert into team(name) values('Exeter City');
insert into team(name) values('Real Racing Club SAD');
insert into team(name) values('Unión Deportiva Las Palmas SAD');
insert into team(name) values('AIK Fotboll');
insert into team(name) values('Milton Keynes Dons');
insert into team(name) values('SK Sturm Graz');
insert into team(name) values('Livorno');
insert into team(name) values('Elche Club De Fútbol SAD');
insert into team(name) values('Accrington Stanley');
insert into team(name) values('SV Josko Ried');
insert into team(name) values('Toluca');
insert into team(name) values('Ascoli');
insert into team(name) values('York City');
insert into team(name) values('New England Revolution');
insert into team(name) values('Sporting Kansas City');
insert into team(name) values('Royal Charleroi SC');
insert into team(name) values('Oxford United FC');
insert into team(name) values('San Luis');
insert into team(name) values('Dijon FCO');
insert into team(name) values('SK Brann');
insert into team(name) values('Córdoba Club De Fútbol SAD');
insert into team(name) values('Bahia');
insert into team(name) values('FC Dallas');
insert into team(name) values('Terek Grozny');
insert into team(name) values('Southend United');
insert into team(name) values('Jaguares De Chiapas');
insert into team(name) values('KSV Cercle Brugge');
insert into team(name) values('Vicenza');
insert into team(name) values('Roda JC');
insert into team(name) values('Helsingborgs IF');
insert into team(name) values('P Warszawa');
insert into team(name) values('FC Union Berlin');
insert into team(name) values('Shamrock Rovers');
insert into team(name) values('Querétaro');
insert into team(name) values('Angers SCO');
insert into team(name) values('Lierse SK');
insert into team(name) values('NEC');
insert into team(name) values('Aldershot Town');
insert into team(name) values('Preston North End');
insert into team(name) values('Huddersfield Town');
insert into team(name) values('Toronto FC');
insert into team(name) values('Rochdale');
insert into team(name) values('NAC Breda');
insert into team(name) values('Wycombe Wanderers');
insert into team(name) values('FSV Frankfurt');
insert into team(name) values('Beerschot AC');
insert into team(name) values('N Recife');
insert into team(name) values('Kuban Krasnodar');
insert into team(name) values('Viking FK');
insert into team(name) values('CD Nacional');
insert into team(name) values('En Avant De Guingamp');
insert into team(name) values('Aberdeen');
insert into team(name) values('Modena');
insert into team(name) values('SC Paderborn');
insert into team(name) values('Leyton Orient');
insert into team(name) values('Jeonbuk Hyundai Motors');
insert into team(name) values('Krylya Sovetov Samara');
insert into team(name) values('Heracles Almelo');
insert into team(name) values('Strømsgodset IF');
insert into team(name) values('G Bełchatów');
insert into team(name) values('RC Recreativo');
insert into team(name) values('La Berrichonne De Châteauroux');
insert into team(name) values('Santa Catarina');
insert into team(name) values('Sporting Lokeren OV');
insert into team(name) values('VVV-Venlo');
insert into team(name) values('Central Coast Mariners FC');
insert into team(name) values('Houston Dynamo');
insert into team(name) values('G Zabrze');
insert into team(name) values('Brentford');
insert into team(name) values('Walsall');
insert into team(name) values('Al-Hilal Saudi FC');
insert into team(name) values('Melbourne Victory FC');
insert into team(name) values('Yeovil Town');
insert into team(name) values('Ponte Preta');
insert into team(name) values('Novara');
insert into team(name) values('Xerez Club Deportivo SAD');
insert into team(name) values('Dynamo Dresden');
insert into team(name) values('Willem II');
insert into team(name) values('Lanciano');
insert into team(name) values('Dagenham And Redbridge');
insert into team(name) values('Grosseto');
insert into team(name) values('Cheltenham Town');
insert into team(name) values('Real Salt Lake');
insert into team(name) values('Morecambe');
insert into team(name) values('Motherwell');
insert into team(name) values('BK Häcken');
insert into team(name) values('Torquay United');
insert into team(name) values('Castellammare Di Stabia');
insert into team(name) values('CS Sedan Ardennes');
insert into team(name) values('Club Deportivo Numancia De Soria SAD');
insert into team(name) values('Hibernian');
insert into team(name) values('Montreal Impact');
insert into team(name) values('Örebro SK');
insert into team(name) values('Burton Albion');
insert into team(name) values('IF Elfsborg');
insert into team(name) values('San Jose Earthquakes');
insert into team(name) values('A Goiânia');
insert into team(name) values('Stabæk Fotball');
insert into team(name) values('FC St Gallen');
insert into team(name) values('Wrocław');
insert into team(name) values('RKC Waalwijk');
insert into team(name) values('Nîmes Olympique');
insert into team(name) values('FC Ingolstadt');
insert into team(name) values('SV Mattersburg');
insert into team(name) values('J Białystok');
insert into team(name) values('Odense Boldklub');
insert into team(name) values('Adelaide United');
insert into team(name) values('KV Mechelen');
insert into team(name) values('Lubin');
insert into team(name) values('FC Erzgebirge Aue');
insert into team(name) values('W Łódź');
insert into team(name) values('Bohemians FC');
insert into team(name) values('Puebla');
insert into team(name) values('Real Murcia CF');
insert into team(name) values('UCD AFC');
insert into team(name) values('AC Arles Avignon');
insert into team(name) values('Ulsan Hyundai Horang-I');
insert into team(name) values('Bury');
insert into team(name) values('Cittadella');
insert into team(name) values('Newcastle United Jets FC');
insert into team(name) values('Carlisle United');
insert into team(name) values('FC Luzern');
insert into team(name) values('FC Rostov');
insert into team(name) values('Gdańsk');
insert into team(name) values('Colchester United');
insert into team(name) values('R Chorzów');
insert into team(name) values('Wellington Phoenix');
insert into team(name) values('FC Wacker Innsbruck');
insert into team(name) values('Philadelphia Union');
insert into team(name) values('Kilmarnock');
insert into team(name) values('Scunthorpe United');
insert into team(name) values('Brisbane Roar Football Club');
insert into team(name) values('Aalesunds FK');
insert into team(name) values('Spezia');
insert into team(name) values('Aalborg BK');
insert into team(name) values('Portland Timbers');
insert into team(name) values('Al-Shabab');
insert into team(name) values('KV Kortrijk');
insert into team(name) values('FC Istres Ouest Provence');
insert into team(name) values('FC Midtjylland');
insert into team(name) values('SC Beira Mar');
insert into team(name) values('Tranmere Rovers');
insert into team(name) values('Crotone');
insert into team(name) values('Alaniya Vladikavkaz');
insert into team(name) values('Bray Wanderers');
insert into team(name) values('Amkar Perm');
insert into team(name) values('Hartlepool United');
insert into team(name) values('Tours FC');
insert into team(name) values('Crawley Town');
insert into team(name) values('Sociedad Deportiva Huesca SAD');
insert into team(name) values('SC Olhanense');
insert into team(name) values('Portuguesa');
insert into team(name) values('Girona Fútbol Club SAD');
insert into team(name) values('Agrupación Deportiva Alcorcón');
insert into team(name) values('St Mirren');
insert into team(name) values('Club León');
insert into team(name) values('Kalmar FF');
insert into team(name) values('Al-Ahli Saudi FC');
insert into team(name) values('RAEC Mons');
insert into team(name) values('S Recife');
insert into team(name) values('Pogoń Szczecin');
insert into team(name) values('Daegu FC');
insert into team(name) values('SangJu Sangmu Phoenix FC');
insert into team(name) values('Esbjerg FB');
insert into team(name) values('Seongnam Ilhwa Chunma');
insert into team(name) values('Inverness Caledonian Thistle');
insert into team(name) values('Bielsko-Biała');
insert into team(name) values('Varese');
insert into team(name) values('Perth Glory FC');
insert into team(name) values('St Patrick''s Athletic');
insert into team(name) values('Daejeon Citizen');
insert into team(name) values('Clermont Foot Auvergne');
insert into team(name) values('Servette FC');
insert into team(name) values('Stade Lavallois Mayenne FC');
insert into team(name) values('AC Horsens');
insert into team(name) values('Jeju United FC');
insert into team(name) values('Sligo Rovers');
insert into team(name) values('Western Sydney Wanderers FC');
insert into team(name) values('SønderjyskE');
insert into team(name) values('FC Trenkwalder Admira');
insert into team(name) values('GAIS');
insert into team(name) values('Chunnam Dragons');
insert into team(name) values('FC Krasnodar');
insert into team(name) values('FC Lausanne-Sports');
insert into team(name) values('Ittihad FC');
insert into team(name) values('Stevenage');
insert into team(name) values('Busan I''Park');
insert into team(name) values('Aarhus GF');
insert into team(name) values('Sociedad Deportiva Ponferradina SAD');
insert into team(name) values('Terni');
insert into team(name) values('Moreira De Cónegos');
insert into team(name) values('Mjällby AIF');
insert into team(name) values('GyeongNam FC');
insert into team(name) values('Pohang Steelers');
insert into team(name) values('Kielce');
insert into team(name) values('Volga Nizhny Novgorod');
insert into team(name) values('Fredrikstad FK');
insert into team(name) values('SSV Jahn Regensburg');
insert into team(name) values('Derry City');
insert into team(name) values('V Barcelos');
insert into team(name) values('St Johnstone FC');
insert into team(name) values('Club Deportivo Guadalajara');
insert into team(name) values('CE Sabadell FC');
insert into team(name) values('FC Thun');
insert into team(name) values('Incheon United FC');
insert into team(name) values('PEC Zwolle');
insert into team(name) values('Chamois Niortais FC');
insert into team(name) values('Randers FC');
insert into team(name) values('IFK Norrkoping');
insert into team(name) values('Drogheda United');
insert into team(name) values('Gefle IF');
insert into team(name) values('Dundalk');
insert into team(name) values('Club Deportivo Mirandés');
insert into team(name) values('Melbourne Heart FC');
insert into team(name) values('SC Wiener Neustadt');
insert into team(name) values('VfR Aalen');
insert into team(name) values('Odd Grenland');
insert into team(name) values('SV Sandhausen');
insert into team(name) values('Hønefoss BK');
insert into team(name) values('Cork City');
insert into team(name) values('Oud-Heverlee Leuven');
insert into team(name) values('Estoril');
insert into team(name) values('Silkeborg IF');
insert into team(name) values('Gazélec FC Ajaccio');
insert into team(name) values('Waasland-Beveren');
insert into team(name) values('FK Haugesund');
insert into team(name) values('Åtvidabergs FF');
insert into team(name) values('Al Nassr FC');
insert into team(name) values('Gangwon FC');
insert into team(name) values('Club Deportivo Lugo');
insert into team(name) values('Mordovia Saransk');
insert into team(name) values('Al-Raed FC');
insert into team(name) values('Al Wehdah Club');
insert into team(name) values('Piast Gliwice');
insert into team(name) values('Wolfsberger AC');
insert into team(name) values('Syrianska');
insert into team(name) values('Alshoulla FC');
insert into team(name) values('Al-Faisaly FC');
insert into team(name) values('Dundee FC');
insert into team(name) values('Al-Fateh FC');
insert into team(name) values('Ross County FC');
insert into team(name) values('Hajer FC');
insert into team(name) values('GIF Sundsvall');
insert into team(name) values('GwangJu FC');
insert into team(name) values('Al-Taawoun FC');
insert into team(name) values('Ettifaq FC');
insert into team(name) values('Sandnes Ulf');
insert into team(name) values('Shelbourne FC');
insert into team(name) values('Najran FC');
insert into team(name) values('Sogndal');
insert into team(name) values('Argentina');
insert into team(name) values('Australia');
insert into team(name) values('Austria');
insert into team(name) values('Belgium');
insert into team(name) values('Bolivia');
insert into team(name) values('Brazil');
insert into team(name) values('Bulgaria');
insert into team(name) values('Camaroon');
insert into team(name) values('Chile');
insert into team(name) values('Colombia');
insert into team(name) values('Côte d’Ivoire');
insert into team(name) values('Czech Republic');
insert into team(name) values('Denmark');
insert into team(name) values('Ecuador');
insert into team(name) values('Egypt');
insert into team(name) values('England');
insert into team(name) values('Finland');
insert into team(name) values('France');
insert into team(name) values('Germany');
insert into team(name) values('Greece');
insert into team(name) values('Hungary');
insert into team(name) values('India');
insert into team(name) values('Ireland');
insert into team(name) values('Italy');
insert into team(name) values('Korea Republic');
insert into team(name) values('Mexico');
insert into team(name) values('Netherlands');
insert into team(name) values('New Zealand');
insert into team(name) values('Northern Ireland');
insert into team(name) values('Norway');
insert into team(name) values('Paraguay');
insert into team(name) values('Peru');
insert into team(name) values('Poland P');
insert into team(name) values('ortugal');
insert into team(name) values('Romania Russia');
insert into team(name) values('Scotland');
insert into team(name) values('Slovenia');
insert into team(name) values('South Africa');
insert into team(name) values('Spain');
insert into team(name) values('Sweden');
insert into team(name) values('Switzerland');
insert into team(name) values('Turkey');
insert into team(name) values('United States');
insert into team(name) values('Uruguay');
insert into team(name) values('Venezuela');

insert into match values (1, '2013-3-04', 1, 1, 2, 2, 2, 2);
insert into match values (2, '2013-3-04', 1, 2, 1, 2, 1, 0);
insert into match values (3, '2013-3-04', 1, 1, 1, 2, 1, 2);


# --- !Downs
delete from record;
delete from player;
delete from team;
delete from match;